minimum_pre_commit_version: 3.2.0  # necessitated by Lucas-C's hooks
default_install_hook_types: [pre-commit, pre-push]
exclude: 'thirdParty'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 0c9f6988b324eb7fc7dcf171bfce13faa9b13ad3  # frozen: v16.0.6
  hooks:
  - id: clang-format
    files: \.(cpp|hpp)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
  hooks:
  - id: no-commit-to-branch
    args: [-b, develop]
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude_types: [markdown, rst]
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: 762c66ea96843b54b936fc680162ea67f85ec2d7  # frozen: v1.5.4
  hooks:
    - id: forbid-tabs
      types_or: [file]
      exclude_types: [rst]
    - id: remove-tabs
      types_or: [file]
      exclude_types: [rst]
    - id: forbid-crlf
    - id: remove-crlf
  # Format all Python scripts
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: c53240a7f974b3707e13eac6710542cc96a2d61a  # frozen: 24.10.0
  hooks:
    - id: black
      name: black Python formatter
      files: ./
      args: [--line-length=100]
