minimum_pre_commit_version: 3.2.0  # necessitated by Lucas-C's hooks
default_install_hook_types: [pre-commit, pre-push]
exclude: 'thirdParty'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    files: \.(cpp|hpp)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: no-commit-to-branch
    args: [-b, develop]
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude_types: [markdown, rst]
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
    - id: forbid-tabs
      types_or: [file]
      exclude_types: [rst]
    - id: remove-tabs
      types_or: [file]
      exclude_types: [rst]
    - id: forbid-crlf
    - id: remove-crlf
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      # The ignores in here are chosen to conform with the currently
      # existing code and not motivated any other way.
      args: [ --fix, --ignore, "F403,F405,E731"]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
      args: ["--line-length", "120"]
