var block_2shared_2Traits_8hpp =
[
    [ "AllocArr", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocArr.html", null ],
    [ "AllocArr<                                                                                                                                                  T,                                                                                                                                           TuiNumElements,                                                                                                                                           TBlockSharedAlloc,                                                                                                                                           typename std::enable_if<                                                                                                                                                                                  std::is_base_of< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value                                                                                                                                                                           &&(!std::is_same< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value)>::type >", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocArr_3_01_01_01_01_01_01_01_01_01_01_01_01_01_04657cf07ac6401e2b73f5381695fa750.html", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocArr_3_01_01_01_01_01_01_01_01_01_01_01_01_01_04657cf07ac6401e2b73f5381695fa750" ],
    [ "AllocVar", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocVar.html", null ],
    [ "AllocVar<                                                                                                                                                  T,                                                                                                                                           TBlockSharedAlloc,                                                                                                                                           typename std::enable_if<                                                                                                                                                                                  std::is_base_of< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value                                                                                                                                                                           &&(!std::is_same< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value)>::type >", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocVar_3_01_01_01_01_01_01_01_01_01_01_01_01_01_027c8166f25597a2e1f0ac244137eb0b5.html", "structalpaka_1_1block_1_1shared_1_1traits_1_1AllocVar_3_01_01_01_01_01_01_01_01_01_01_01_01_01_027c8166f25597a2e1f0ac244137eb0b5" ],
    [ "FreeMem", "structalpaka_1_1block_1_1shared_1_1traits_1_1FreeMem.html", null ],
    [ "FreeMem<                                                                                                                                                  TBlockSharedAlloc,                                                                                                                                           typename std::enable_if<                                                                                                                                                                                  std::is_base_of< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value                                                                                                                                                                           &&(!std::is_same< typename TBlockSharedAlloc::BlockSharedAllocBase, typename std::decay< TBlockSharedAlloc >::type >::value)>::type >", "structalpaka_1_1block_1_1shared_1_1traits_1_1FreeMem_3_01_01_01_01_01_01_01_01_01_01_01_01_01_01e0479a2723187872a690108131e9ea4d.html", "structalpaka_1_1block_1_1shared_1_1traits_1_1FreeMem_3_01_01_01_01_01_01_01_01_01_01_01_01_01_01e0479a2723187872a690108131e9ea4d" ],
    [ "allocArr", "block_2shared_2Traits_8hpp.html#a73e14e8439ed038971814d5549cae2a3", null ],
    [ "allocVar", "block_2shared_2Traits_8hpp.html#ac4e4832a6cafe90c41d54400cdd27074", null ],
    [ "freeMem", "block_2shared_2Traits_8hpp.html#a48edf6062776b2bfc5a994c6638b4771", null ]
];