name: Continuous Integration

on: [push, pull_request]

env:
  ALPAKA_CI: GITHUB
  TBB_ROOT: tbb
  BOOST_ROOT: boost
  ALPAKA_CI_BOOST_LIB_DIR: boost_libs
  ALPAKA_CI_CLANG_DIR: llvm
  ALPAKA_CI_CMAKE_DIR: CMake
  ALPAKA_CI_CUDA_DIR: CUDA
  ALPAKA_CI_HIP_ROOT_DIR: hip
  ALPAKA_CI_SANITIZERS:
  ALPAKA_CI_ANALYSIS: OFF
  ALPAKA_ACC_GPU_CUDA_ENABLE: OFF
  ALPAKA_ACC_GPU_HIP_ENABLE: OFF

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          windows_cl-2019_debug_analysis,
          macos_xcode-11.3_debug_analysis,
          macos_xcode-11_debug,
          macos_xcode-11_release,
          macos_xcode-11.1_debug,
          macos_xcode-11.1_release,
          macos_xcode-11.2_debug,
          macos_xcode-11.2_release,
          macos_xcode-11.3_debug,
          macos_xcode-11.3_release,
          macos_xcode-11.4_debug,
          macos_xcode-11.4_release,
          windows_cl-2017_release,
          windows_cl-2017_debug,
          windows_cl-2019_release,
          windows_cl-2019_debug,
          windows_nvcc-10.0_cl-2017_release_cuda-only_separable-compilation,
          windows_nvcc-10.0_cl-2017_debug,
          windows_nvcc-10.1_cl-2017_debug_cuda-only,
          windows_nvcc-10.1_cl-2017_release,
          windows_nvcc-10.2_cl-2017_debug_cuda-only,
          windows_nvcc-10.2_cl-2017_release,
        ]

        include:
        ### Analysis builds
        - name: windows_cl-2019_debug_analysis
          os: windows-2019
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2019,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.73.0, ALPAKA_CI_CMAKE_VER: 3.16.5, ALPAKA_CI_ANALYSIS: ON, ALPAKA_DEBUG: 2}
        - name: macos_xcode-11.3_debug_analysis
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.3.1, CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.65.1,                              ALPAKA_CI_ANALYSIS: ON, ALPAKA_DEBUG: 2, ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}

        ### macOS
        - name: macos_xcode-11_debug
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11,     CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.67.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_CXX_STANDARD: 17}
        - name: macos_xcode-11_release
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11,     CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.66.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}
        - name: macos_xcode-11.1_debug
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.1,   CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.65.1,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}
        - name: macos_xcode-11.1_release
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.1,   CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.72.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_CXX_STANDARD: 17}
        - name: macos_xcode-11.2_debug
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.2.1, CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.66.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_CXX_STANDARD: 17}
        - name: macos_xcode-11.2_release
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.2.1, CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.65.1,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}
        - name: macos_xcode-11.3_debug
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.3.1, CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.67.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_CXX_STANDARD: 17}
        - name: macos_xcode-11.3_release
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.3.1, CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.73.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}
        - name: macos_xcode-11.4_debug
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.4,   CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.65.1,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF}
        - name: macos_xcode-11.4_release
          os: macos-10.15
          env: {TRAVIS_OS_NAME: osx,     CXX: clang++, CC: clang,  ALPAKA_CI_XCODE_VER: 11.4,   CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.67.0,                                                  ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_CXX_STANDARD: 17}

        ### Windows
        - name: windows_cl-2017_release
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.71.0, ALPAKA_CI_CMAKE_VER: 3.16.5, OMP_NUM_THREADS: 4, ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE: OFF, ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE: OFF, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}
        - name: windows_cl-2017_debug
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.65.1, ALPAKA_CI_CMAKE_VER: 3.17.1, OMP_NUM_THREADS: 3, ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE: OFF, ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE: OFF, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF,  ALPAKA_CXX_STANDARD: 17}
        - name: windows_cl-2019_release
          os: windows-2019
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2019,      CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.70.0, ALPAKA_CI_CMAKE_VER: 3.17.1, OMP_NUM_THREADS: 1, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}
        - name: windows_cl-2019_debug
          os: windows-2019
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2019,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.72.0, ALPAKA_CI_CMAKE_VER: 3.16.5, OMP_NUM_THREADS: 4, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}

        ## CUDA 10.0
        # nvcc + MSVC
        - name: windows_nvcc-10.0_cl-2017_release_cuda-only_separable-compilation
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.67.0, ALPAKA_CI_CMAKE_VER: 3.17.1,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.0", ALPAKA_CUDA_ARCH: "30;75", ALPAKA_ACC_GPU_CUDA_ONLY_MODE: ON, ALPAKA_CUDA_NVCC_SEPARABLE_COMPILATION: ON}
        - name: windows_nvcc-10.0_cl-2017_debug
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.69.0, ALPAKA_CI_CMAKE_VER: 3.16.5,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.0", ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE: OFF, ALPAKA_ACC_CPU_BT_OMP4_ENABLE: OFF, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}

        ## CUDA 10.1
        # nvcc + MSVC
        - name: windows_nvcc-10.1_cl-2017_debug_cuda-only
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.70.0, ALPAKA_CI_CMAKE_VER: 3.16.5,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.1", ALPAKA_CUDA_ARCH: "30;75", ALPAKA_ACC_GPU_CUDA_ONLY_MODE: ON}
        - name: windows_nvcc-10.1_cl-2017_release
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.65.1, ALPAKA_CI_CMAKE_VER: 3.17.1,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.1", ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE: OFF, ALPAKA_ACC_CPU_BT_OMP4_ENABLE: OFF, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}

        ## CUDA 10.2
        # nvcc + MSVC
        - name: windows_nvcc-10.2_cl-2017_debug_cuda-only
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Debug,   ALPAKA_CI_BOOST_BRANCH: boost-1.73.0, ALPAKA_CI_CMAKE_VER: 3.17.1,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.2", ALPAKA_CUDA_ARCH: "30;75", ALPAKA_ACC_GPU_CUDA_ONLY_MODE: ON}
        - name: windows_nvcc-10.2_cl-2017_release
          os: windows-2016
          env: {TRAVIS_OS_NAME: windows, CXX: cl.exe,  CC: cl.exe, ALPAKA_CI_CL_VER: 2017,      CMAKE_BUILD_TYPE: Release, ALPAKA_CI_BOOST_BRANCH: boost-1.68.0, ALPAKA_CI_CMAKE_VER: 3.16.5,                     ALPAKA_ACC_GPU_CUDA_ENABLE: ON, ALPAKA_CUDA_VERSION: "10.2", ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE: OFF, ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE: OFF, ALPAKA_ACC_CPU_BT_OMP4_ENABLE: OFF, ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE: OFF}

    steps:
    - uses: actions/checkout@v1
    - name: build + test
      if: runner.os == 'Windows'
      shell: bash
      run: cd ${GITHUB_WORKSPACE} && ./script/ci.sh
    - name: build + test
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: cd ${GITHUB_WORKSPACE} && ./script/ci.sh
