name: CI Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# Stop CI for the PR if the PR is updates.
# Stop CI runs for dev branch if a new PR is merged into the dev branch.
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || format('ref-{0}', github.ref) }}
  cancel-in-progress: true

env:
  alpaka_cmake_flags: "-Dalpaka_COMPILE_PEDANTIC=ON -Dalpaka_DOCS=ON -Dalpaka_TESTS=ON -Dalpaka_BENCHMARKS=ON -Dalpaka_EXAMPLES=ON -Dalpaka_HEADERCHECKS=ON -Dalpaka_LOG=dynamic -Dalpaka_FAST_MATH=OFF"
  APCI_ALPAKA_ROOT: ${{ github.workspace }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install pre-commit==4.3.0
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

  ci:
    # Default runner for non-CUDA/HIP tests; overridden for CUDA/HIP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { compiler: gcc, version: "12", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : gcc@12, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: gcc, version: "13", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          # tbb backend on
          - { compiler: gcc, version: "13", cuda: "no", hip: "no", container: "ubuntu:24.04", tbb: "on",
              env : {APCI_DEVICE_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_TBB: ON,  APCI_RUN_CTEST: ON} }
          - { compiler: gcc, version: "14", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER: gcc@14, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: gcc, version: "15", cuda: "no", hip: "no", container: "gcc:15.1.0",
              env : {APCI_DEVICE_COMPILER: gcc@15, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: gcc, version: "15", cuda: "no", hip: "no", container: "gcc:15.1.0" , simd: "EMULATION", hwloc: "no",
              env : {APCI_DEVICE_COMPILER: gcc@15, APCI_CMAKE : 3.25.1, APCI_RUN_CTEST: ON} }
          # clang host compiler
          - { compiler: clang, version: "17", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : clang@17, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "18", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : clang@18, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "19", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : clang@19, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "20", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : clang@20, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "21", cuda: "no", hip: "no", container: "ubuntu:24.04",
              env : {APCI_DEVICE_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "21", cuda: "no", hip: "no", container: "ubuntu:24.04", simd: "EMULATION", hwloc: "no",
              env : {APCI_DEVICE_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_RUN_CTEST: ON} }
          - { compiler: clang, version: "21", cuda: "no", hip: "no", container: "ubuntu:24.04", tbb: "on",
              env : {APCI_DEVICE_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_TBB: ON, APCI_RUN_CTEST: ON} }
          # nvcc CUDA (nvcc does not contain simd option because nvcc can not use std::simd and is always using simd emulation
          - { compiler: nvcc, version: "", cuda: "12.5", hip: "no", container: "nvidia/cuda:12.5.1-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@12.5, APCI_HOST_COMPILER : gcc@13 ,APCI_CMAKE : 3.28.3, APCI_CUDA: 12.5, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "12.6", hip: "no", container: "nvidia/cuda:12.6.3-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@12.6, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.6, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "12.8", hip: "no", container: "nvidia/cuda:12.8.1-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@12.8, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.8, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "12.9", hip: "no", container: "nvidia/cuda:12.9.1-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@12.9, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.9, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "13.0", hip: "no", container: "nvidia/cuda:13.0.0-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@13.0, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 13.0, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "13.1", hip: "no", container: "nvidia/cuda:13.1.0-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@13.1, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 13.1, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "13.2", hip: "no", container: "nvidia/cuda:13.2.0-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : nvcc@13.2, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 13.2, APCI_RUN_CTEST: OFF} }
          - { compiler: nvcc, version: "", cuda: "13.3", hip: "no", container: "nvidia/cuda:13.3.0-devel-ubuntu24.04",
              env: { APCI_DEVICE_COMPILER: nvcc@13.3, APCI_HOST_COMPILER : gcc@13, APCI_CMAKE : 3.28.3, APCI_CUDA: 13.3, APCI_RUN_CTEST: OFF } }
          # nvcc + clang
          - { compiler: nvcc, version: "", cuda: "13.3", hip: "no", container: "nvidia/cuda:13.3.0-devel-ubuntu24.04",
              env: { APCI_DEVICE_COMPILER: nvcc@13.3, APCI_HOST_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_CUDA: 13.3, APCI_RUN_CTEST: OFF } }
          # clang-cuda (device compile with clang)
          - { compiler: clang, version: "20", cuda: "12.8", hip: "no", container: "nvidia/cuda:12.8.1-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : clang@20, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.8, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "21", cuda: "12.8", hip: "no", container: "nvidia/cuda:12.8.1-devel-ubuntu24.04",
              env : {APCI_DEVICE_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.8, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "21", cuda: "12.8", hip: "no", container: "nvidia/cuda:12.8.1-devel-ubuntu24.04", simd: "EMULATION", hwloc: "no",
              env : {APCI_DEVICE_COMPILER : clang@21, APCI_CMAKE : 3.28.3, APCI_CUDA: 12.8, APCI_RUN_CTEST: OFF} }
          # clang with ROCm HIP
          - { compiler: clang, version: "18", cuda: "no", hip: "6.2.4", container: "rocm/dev-ubuntu-24.04:6.2.4",
              env : {APCI_DEVICE_COMPILER : clang@18, APCI_CMAKE : 3.28.3, APCI_HIP: 6.2.4, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "18", cuda: "no", hip: "6.3.4", container: "rocm/dev-ubuntu-24.04:6.3.4",
              env : {APCI_DEVICE_COMPILER : clang@18, APCI_CMAKE : 3.28.3, APCI_HIP: 6.3.4, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "19", cuda: "no", hip: "6.4.2", container: "rocm/dev-ubuntu-24.04:6.4.2",
              env : {APCI_DEVICE_COMPILER : clang@19, APCI_CMAKE : 3.28.3, APCI_HIP: 6.4.2, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "20", cuda: "no", hip: "7.0", container: "rocm/dev-ubuntu-24.04:7.0",
              env : {APCI_DEVICE_COMPILER : clang@20, APCI_CMAKE : 3.28.3, APCI_HIP: 7.0, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "20", cuda: "no", hip: "7.1", container: "rocm/dev-ubuntu-24.04:7.1",
              env : {APCI_DEVICE_COMPILER : clang@20, APCI_CMAKE : 3.28.3, APCI_HIP: 7.1, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "22", cuda: "no", hip: "7.2", container: "rocm/dev-ubuntu-24.04:7.2",
              env : {APCI_DEVICE_COMPILER : clang@22, APCI_CMAKE : 3.28.3, APCI_HIP: 7.2, APCI_RUN_CTEST: OFF} }
          - { compiler: clang, version: "22", cuda: "no", hip: "7.2", container: "rocm/dev-ubuntu-24.04:7.2", simd: "EMULATION", hwloc: "no",
              env : {APCI_DEVICE_COMPILER : clang@22, APCI_CMAKE : 3.28.3, APCI_HIP: 7.2, APCI_RUN_CTEST: OFF} }
          # SYCL
          - { compiler: icpx, version: "2025.1", cuda: "no", hip: "no", container: "intel/oneapi-hpckit:2025.1.3-0-devel-ubuntu24.04",
              env : { APCI_DEVICE_COMPILER : icpx@2025.1, APCI_CMAKE : 3.28.3, APCI_ONEAPI: 2025.1, APCI_ONEAPI_TARGET: cpu, APCI_RUN_CTEST: OFF} }
          - { compiler: icpx, version: "2025.2", cuda: "no", hip: "no", container: "intel/oneapi-hpckit:2025.2.2-0-devel-ubuntu24.04",
              env : { APCI_DEVICE_COMPILER : icpx@2025.2, APCI_CMAKE : 3.28.3, APCI_ONEAPI: 2025.2, APCI_ONEAPI_TARGET: cpu, APCI_RUN_CTEST: OFF} }
          - { compiler: icpx, version: "2025.3", cuda: "no", hip: "no", container: "intel/oneapi-hpckit:2025.3.0-0-devel-ubuntu24.04",
              env : { APCI_DEVICE_COMPILER : icpx@2025.3, APCI_CMAKE : 3.28.3, APCI_ONEAPI: 2025.3, APCI_ONEAPI_TARGET: cpu, APCI_RUN_CTEST: OFF} }
          - { compiler: icpx, version: "2026.0", cuda: "no", hip: "no", container: "intel/oneapi:2026.0.0-devel-ubuntu24.04",
              env: { APCI_DEVICE_COMPILER: icpx@2026.0, APCI_CMAKE: 3.28.3, APCI_ONEAPI: 2026.0, APCI_ONEAPI_TARGET: cpu, APCI_RUN_CTEST: OFF} }
          - { compiler: icpx, version: "2026.0", cuda: "no", hip: "no", container: "intel/oneapi:2026.0.0-devel-ubuntu24.04", simd: "EMULATION", hwloc: "no",
              env: { APCI_DEVICE_COMPILER: icpx@2026.0, APCI_CMAKE: 3.28.3, APCI_ONEAPI: 2026.0, APCI_ONEAPI_TARGET: cpu, APCI_RUN_CTEST: OFF} }
          # Use/validate oneAPI-provided oneTBB package with the latest icpx toolchain
          - { compiler: icpx, version: "2026.0", cuda: "no", hip: "no", container: "intel/oneapi:2026.0.0-devel-ubuntu24.04", tbb: "on",
              env: { APCI_DEVICE_COMPILER: icpx@2026.0, APCI_CMAKE: 3.28.3, APCI_ONEAPI: 2026.0, APCI_ONEAPI_TARGET: cpu, APCI_TBB: ON, APCI_RUN_CTEST: ON} }
      fail-fast: false

    # Specify the container to use based on the matrix configuration
    container:
      image: ${{ matrix.config.container }}

    env: ${{ matrix.config.env }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v6
      - name: export GitHub Actions variables to environment variables
        run: |
            echo "APCI_IMAGE_NAME=${{ matrix.config.container }}" >> $GITHUB_ENV
            if [ "${{ github.event_name }}" = "pull_request" ]; then
                echo "APCI_GIT_URL=${{ github.event.pull_request.head.repo.clone_url }}" >> $GITHUB_ENV
                echo "APCI_BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            else
                echo "APCI_GIT_URL=https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
                echo "APCI_BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
            fi
            ${{ matrix.config.hwloc == 'no' }} && echo "APCI_HWLOC=OFF" >> $GITHUB_ENV || true
            ${{ matrix.config.sanitizer == 'asan' }}  && echo 'APCI_SANITIZER_ASAN=ON'  >> $GITHUB_ENV || true
            ${{ matrix.config.sanitizer == 'tsan' }}  && echo 'APCI_SANITIZER_TSAN=ON'  >> $GITHUB_ENV || true
            ${{ matrix.config.sanitizer == 'lsan' }}  && echo 'APCI_SANITIZER_LSAN=ON'  >> $GITHUB_ENV || true
            ${{ matrix.config.sanitizer == 'ubsan' }} && echo 'APCI_SANITIZER_UBSAN=ON' >> $GITHUB_ENV || true
            ${{ matrix.config.simd != '' }} && echo 'APCI_SIMD=${{matrix.config.simd}}'  >> $GITHUB_ENV || true

      - name: job configuration environment variables
        run: "${APCI_ALPAKA_ROOT}/script/ci/info.sh"

      # Install base dependencies
      - name: Install base dependencies
        run: |
          "${APCI_ALPAKA_ROOT}/script/ci/install/basic.sh"

      - name: Install CMake
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/cmake.sh"

      - name: Install GCC
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/gcc.sh"

      - name: Install Clang
        shell: bash
        if: (matrix.config.compiler == 'clang' || matrix.config.compiler == 'nvcc') && matrix.config.hip == 'no'
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/clang.sh"

      - name: Install CUDA
        if: matrix.config.cuda != 'no'
        shell: bash
        run: $APCI_ALPAKA_ROOT/script/ci/install/cuda.sh

      - name: Install ROCm
        if: matrix.config.hip != 'no'
        shell: bash
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/rocm.sh"

      - name: Install oneAPI
        if: matrix.config.compiler == 'icpx'
        shell: bash
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/oneapi.sh"

      - name: Install oneTBB
        if: matrix.config.tbb == 'on' && matrix.config.compiler != 'icpx'
        shell: bash
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/tbb.sh"

      # hwloc (opt out)
      - name: Install hwloc
        if: matrix.config.hwloc != 'no'
        shell: bash
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/hwloc.sh"

      - name: Setup Sanitizer
        if: matrix.config.sanitizer
        run: "${APCI_ALPAKA_ROOT}/script/ci/install/sanitizer.sh"

      # Configure CMake with the selected compiler and options
      - name: Configure CMake
        run: "${APCI_ALPAKA_ROOT}/script/ci/configure.sh"

      - name: Compile Code
        run: "${APCI_ALPAKA_ROOT}/script/ci/build.sh"

      - name: Run tests
        if: matrix.config.cuda == 'no' && matrix.config.hip == 'no'
        run: "${APCI_ALPAKA_ROOT}/script/ci/test.sh"

  # Check that all generated matrix jobs passed
  # This job allow us to add 'ci-jobmatrix' as required job in GitHub and never miss marking matrix jobs as
  # required check. This avoids that we merge broken PR's and is workarounding an issue of GitHub that
  # The names selectable as required jobs not match the names shown at the end of each PR.
  ci-jobmatrix:
    name: ci-jobmatrix
    runs-on: ubuntu-latest
    needs: [ci]
    if: always()
    steps:
      - name: Check matrix result
        run: |
          if [ "${{ needs.ci.result }}" != "success" ]; then
            echo "Matrix CI failed: ${{ needs.ci.result }}"
            exit 1
          fi

  # We use only a single gcc version to check the coverage.
  # Therefore, the results will be a ruf coverage overview.
  coverage:
    name: coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 ninja-build gcovr libhwloc-dev pkg-config

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER=g++-13 \
            -Dalpaka_TESTS=ON \
            -Dalpaka_EXAMPLES=OFF \
            -Dalpaka_BENCHMARKS=OFF \
            -Dalpaka_DOCS=OFF \
            -Dalpaka_HEADERCHECKS=OFF \
            -Dalpaka_DEP_HWLOC=ON \
            -Dalpaka_DEP_OMP=ON \
            -Dalpaka_COVERAGE=ON

      - name: Build
        run: cmake --build build -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage report
        run: |
          gcovr \
            --root . \
            --filter 'include/' \
            --exclude 'test/' \
            --exclude 'example/' \
            --exclude 'benchmark/' \
            --cobertura-pretty \
            --output build/coverage.xml \
            build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.xml
          disable_search: true
          fail_ci_if_error: true
          flags: cpu
          name: cpu-coverage
          use_oidc: true
